# Generated by Django 5.1.7 on 2025-03-21 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Test_ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Access_Token', models.CharField(max_length=150)),
                ('Name_Test', models.CharField(max_length=150)),
                ('Discription', models.CharField(max_length=150)),
                ('Start_Time', models.DateTimeField()),
                ('End_Time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Enrolment_no', models.CharField(max_length=150)),
                ('RiskScore', models.CharField(max_length=100)),
                ('Image_URL', models.URLField(max_length=500)),
                ('Test_ClassRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.create_test_classroom')),
            ],
        ),
    ]
