# Generated by Django 5.1.7 on 2025-03-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_test_classroom',
            name='Access_Token',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
