# Generated by Django 5.1.7 on 2025-03-22 06:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_test_classroom',
            name='App_Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
