# Generated by Django 5.1.7 on 2025-03-22 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_create_test_classroom_app_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_code', models.CharField(max_length=150)),
                ('Test_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.create_test_classroom')),
            ],
        ),
    ]
