# Generated by Django 5.1.7 on 2025-03-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_test_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_codes',
            name='Test_code',
            field=models.CharField(max_length=500),
        ),
    ]
