# Generated by Django 5.1.7 on 2025-03-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_alter_test_codes_test_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_response',
            name='Image_URL',
            field=models.URLField(max_length=800),
        ),
    ]
